// Code generated by ent, DO NOT EDIT.

package ent

import (
	"DemoApp/ent/history"
	"DemoApp/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// HistoryUpdate is the builder for updating History entities.
type HistoryUpdate struct {
	config
	hooks    []Hook
	mutation *HistoryMutation
}

// Where appends a list predicates to the HistoryUpdate builder.
func (hu *HistoryUpdate) Where(ps ...predicate.History) *HistoryUpdate {
	hu.mutation.Where(ps...)
	return hu
}

// SetTableName sets the "table_name" field.
func (hu *HistoryUpdate) SetTableName(s string) *HistoryUpdate {
	hu.mutation.SetTableName(s)
	return hu
}

// SetNillableTableName sets the "table_name" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableTableName(s *string) *HistoryUpdate {
	if s != nil {
		hu.SetTableName(*s)
	}
	return hu
}

// SetRecordID sets the "record_id" field.
func (hu *HistoryUpdate) SetRecordID(s string) *HistoryUpdate {
	hu.mutation.SetRecordID(s)
	return hu
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableRecordID(s *string) *HistoryUpdate {
	if s != nil {
		hu.SetRecordID(*s)
	}
	return hu
}

// SetAction sets the "action" field.
func (hu *HistoryUpdate) SetAction(s string) *HistoryUpdate {
	hu.mutation.SetAction(s)
	return hu
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableAction(s *string) *HistoryUpdate {
	if s != nil {
		hu.SetAction(*s)
	}
	return hu
}

// SetOldData sets the "old_data" field.
func (hu *HistoryUpdate) SetOldData(m map[string]interface{}) *HistoryUpdate {
	hu.mutation.SetOldData(m)
	return hu
}

// ClearOldData clears the value of the "old_data" field.
func (hu *HistoryUpdate) ClearOldData() *HistoryUpdate {
	hu.mutation.ClearOldData()
	return hu
}

// SetNewData sets the "new_data" field.
func (hu *HistoryUpdate) SetNewData(m map[string]interface{}) *HistoryUpdate {
	hu.mutation.SetNewData(m)
	return hu
}

// ClearNewData clears the value of the "new_data" field.
func (hu *HistoryUpdate) ClearNewData() *HistoryUpdate {
	hu.mutation.ClearNewData()
	return hu
}

// SetUserID sets the "user_id" field.
func (hu *HistoryUpdate) SetUserID(s string) *HistoryUpdate {
	hu.mutation.SetUserID(s)
	return hu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (hu *HistoryUpdate) SetNillableUserID(s *string) *HistoryUpdate {
	if s != nil {
		hu.SetUserID(*s)
	}
	return hu
}

// ClearUserID clears the value of the "user_id" field.
func (hu *HistoryUpdate) ClearUserID() *HistoryUpdate {
	hu.mutation.ClearUserID()
	return hu
}

// SetMetadata sets the "metadata" field.
func (hu *HistoryUpdate) SetMetadata(m map[string]interface{}) *HistoryUpdate {
	hu.mutation.SetMetadata(m)
	return hu
}

// ClearMetadata clears the value of the "metadata" field.
func (hu *HistoryUpdate) ClearMetadata() *HistoryUpdate {
	hu.mutation.ClearMetadata()
	return hu
}

// Mutation returns the HistoryMutation object of the builder.
func (hu *HistoryUpdate) Mutation() *HistoryMutation {
	return hu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (hu *HistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, hu.sqlSave, hu.mutation, hu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (hu *HistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := hu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (hu *HistoryUpdate) Exec(ctx context.Context) error {
	_, err := hu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hu *HistoryUpdate) ExecX(ctx context.Context) {
	if err := hu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (hu *HistoryUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeString))
	if ps := hu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := hu.mutation.TableName(); ok {
		_spec.SetField(history.FieldTableName, field.TypeString, value)
	}
	if value, ok := hu.mutation.RecordID(); ok {
		_spec.SetField(history.FieldRecordID, field.TypeString, value)
	}
	if value, ok := hu.mutation.Action(); ok {
		_spec.SetField(history.FieldAction, field.TypeString, value)
	}
	if value, ok := hu.mutation.OldData(); ok {
		_spec.SetField(history.FieldOldData, field.TypeJSON, value)
	}
	if hu.mutation.OldDataCleared() {
		_spec.ClearField(history.FieldOldData, field.TypeJSON)
	}
	if value, ok := hu.mutation.NewData(); ok {
		_spec.SetField(history.FieldNewData, field.TypeJSON, value)
	}
	if hu.mutation.NewDataCleared() {
		_spec.ClearField(history.FieldNewData, field.TypeJSON)
	}
	if value, ok := hu.mutation.UserID(); ok {
		_spec.SetField(history.FieldUserID, field.TypeString, value)
	}
	if hu.mutation.UserIDCleared() {
		_spec.ClearField(history.FieldUserID, field.TypeString)
	}
	if value, ok := hu.mutation.Metadata(); ok {
		_spec.SetField(history.FieldMetadata, field.TypeJSON, value)
	}
	if hu.mutation.MetadataCleared() {
		_spec.ClearField(history.FieldMetadata, field.TypeJSON)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, hu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	hu.mutation.done = true
	return n, nil
}

// HistoryUpdateOne is the builder for updating a single History entity.
type HistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HistoryMutation
}

// SetTableName sets the "table_name" field.
func (huo *HistoryUpdateOne) SetTableName(s string) *HistoryUpdateOne {
	huo.mutation.SetTableName(s)
	return huo
}

// SetNillableTableName sets the "table_name" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableTableName(s *string) *HistoryUpdateOne {
	if s != nil {
		huo.SetTableName(*s)
	}
	return huo
}

// SetRecordID sets the "record_id" field.
func (huo *HistoryUpdateOne) SetRecordID(s string) *HistoryUpdateOne {
	huo.mutation.SetRecordID(s)
	return huo
}

// SetNillableRecordID sets the "record_id" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableRecordID(s *string) *HistoryUpdateOne {
	if s != nil {
		huo.SetRecordID(*s)
	}
	return huo
}

// SetAction sets the "action" field.
func (huo *HistoryUpdateOne) SetAction(s string) *HistoryUpdateOne {
	huo.mutation.SetAction(s)
	return huo
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableAction(s *string) *HistoryUpdateOne {
	if s != nil {
		huo.SetAction(*s)
	}
	return huo
}

// SetOldData sets the "old_data" field.
func (huo *HistoryUpdateOne) SetOldData(m map[string]interface{}) *HistoryUpdateOne {
	huo.mutation.SetOldData(m)
	return huo
}

// ClearOldData clears the value of the "old_data" field.
func (huo *HistoryUpdateOne) ClearOldData() *HistoryUpdateOne {
	huo.mutation.ClearOldData()
	return huo
}

// SetNewData sets the "new_data" field.
func (huo *HistoryUpdateOne) SetNewData(m map[string]interface{}) *HistoryUpdateOne {
	huo.mutation.SetNewData(m)
	return huo
}

// ClearNewData clears the value of the "new_data" field.
func (huo *HistoryUpdateOne) ClearNewData() *HistoryUpdateOne {
	huo.mutation.ClearNewData()
	return huo
}

// SetUserID sets the "user_id" field.
func (huo *HistoryUpdateOne) SetUserID(s string) *HistoryUpdateOne {
	huo.mutation.SetUserID(s)
	return huo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (huo *HistoryUpdateOne) SetNillableUserID(s *string) *HistoryUpdateOne {
	if s != nil {
		huo.SetUserID(*s)
	}
	return huo
}

// ClearUserID clears the value of the "user_id" field.
func (huo *HistoryUpdateOne) ClearUserID() *HistoryUpdateOne {
	huo.mutation.ClearUserID()
	return huo
}

// SetMetadata sets the "metadata" field.
func (huo *HistoryUpdateOne) SetMetadata(m map[string]interface{}) *HistoryUpdateOne {
	huo.mutation.SetMetadata(m)
	return huo
}

// ClearMetadata clears the value of the "metadata" field.
func (huo *HistoryUpdateOne) ClearMetadata() *HistoryUpdateOne {
	huo.mutation.ClearMetadata()
	return huo
}

// Mutation returns the HistoryMutation object of the builder.
func (huo *HistoryUpdateOne) Mutation() *HistoryMutation {
	return huo.mutation
}

// Where appends a list predicates to the HistoryUpdate builder.
func (huo *HistoryUpdateOne) Where(ps ...predicate.History) *HistoryUpdateOne {
	huo.mutation.Where(ps...)
	return huo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (huo *HistoryUpdateOne) Select(field string, fields ...string) *HistoryUpdateOne {
	huo.fields = append([]string{field}, fields...)
	return huo
}

// Save executes the query and returns the updated History entity.
func (huo *HistoryUpdateOne) Save(ctx context.Context) (*History, error) {
	return withHooks(ctx, huo.sqlSave, huo.mutation, huo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (huo *HistoryUpdateOne) SaveX(ctx context.Context) *History {
	node, err := huo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (huo *HistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := huo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (huo *HistoryUpdateOne) ExecX(ctx context.Context) {
	if err := huo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (huo *HistoryUpdateOne) sqlSave(ctx context.Context) (_node *History, err error) {
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeString))
	id, ok := huo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "History.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := huo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, history.FieldID)
		for _, f := range fields {
			if !history.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != history.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := huo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := huo.mutation.TableName(); ok {
		_spec.SetField(history.FieldTableName, field.TypeString, value)
	}
	if value, ok := huo.mutation.RecordID(); ok {
		_spec.SetField(history.FieldRecordID, field.TypeString, value)
	}
	if value, ok := huo.mutation.Action(); ok {
		_spec.SetField(history.FieldAction, field.TypeString, value)
	}
	if value, ok := huo.mutation.OldData(); ok {
		_spec.SetField(history.FieldOldData, field.TypeJSON, value)
	}
	if huo.mutation.OldDataCleared() {
		_spec.ClearField(history.FieldOldData, field.TypeJSON)
	}
	if value, ok := huo.mutation.NewData(); ok {
		_spec.SetField(history.FieldNewData, field.TypeJSON, value)
	}
	if huo.mutation.NewDataCleared() {
		_spec.ClearField(history.FieldNewData, field.TypeJSON)
	}
	if value, ok := huo.mutation.UserID(); ok {
		_spec.SetField(history.FieldUserID, field.TypeString, value)
	}
	if huo.mutation.UserIDCleared() {
		_spec.ClearField(history.FieldUserID, field.TypeString)
	}
	if value, ok := huo.mutation.Metadata(); ok {
		_spec.SetField(history.FieldMetadata, field.TypeJSON, value)
	}
	if huo.mutation.MetadataCleared() {
		_spec.ClearField(history.FieldMetadata, field.TypeJSON)
	}
	_node = &History{config: huo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, huo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	huo.mutation.done = true
	return _node, nil
}
