// Code generated by ent, DO NOT EDIT.

package ent

import (
	"DemoApp/ent/class"
	"DemoApp/ent/history"
	"DemoApp/ent/schema"
	"DemoApp/ent/student"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	classFields := schema.Class{}.Fields()
	_ = classFields
	// classDescIsDeleted is the schema descriptor for is_deleted field.
	classDescIsDeleted := classFields[2].Descriptor()
	// class.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	class.DefaultIsDeleted = classDescIsDeleted.Default.(bool)
	historyFields := schema.History{}.Fields()
	_ = historyFields
	// historyDescCreatedAt is the schema descriptor for created_at field.
	historyDescCreatedAt := historyFields[7].Descriptor()
	// history.DefaultCreatedAt holds the default value on creation for the created_at field.
	history.DefaultCreatedAt = historyDescCreatedAt.Default.(func() time.Time)
	studentFields := schema.Student{}.Fields()
	_ = studentFields
	// studentDescIsDeleted is the schema descriptor for is_deleted field.
	studentDescIsDeleted := studentFields[2].Descriptor()
	// student.DefaultIsDeleted holds the default value on creation for the is_deleted field.
	student.DefaultIsDeleted = studentDescIsDeleted.Default.(bool)
}
