// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/helloworld/v1/class.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Grade         int64                  `protobuf:"varint,2,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClassRequest) Reset() {
	*x = CreateClassRequest{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClassRequest) ProtoMessage() {}

func (x *CreateClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClassRequest.ProtoReflect.Descriptor instead.
func (*CreateClassRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{0}
}

func (x *CreateClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateClassRequest) GetGrade() int64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

type UpdateClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // ID của lớp học cần cập nhật
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`    // Tên lớp học mới
	Grade         int64                  `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"` // Lớp học mới
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClassRequest) Reset() {
	*x = UpdateClassRequest{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClassRequest) ProtoMessage() {}

func (x *UpdateClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClassRequest.ProtoReflect.Descriptor instead.
func (*UpdateClassRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateClassRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateClassRequest) GetGrade() int64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

type DeleteClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID của lớp học cần xóa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClassRequest) Reset() {
	*x = DeleteClassRequest{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassRequest) ProtoMessage() {}

func (x *DeleteClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassRequest.ProtoReflect.Descriptor instead.
func (*DeleteClassRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteClassRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                                  // Số trang
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`          // Số lượng bản ghi trên mỗi trang
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`                             // Tên lớp học để lọc
	Grade         *int64                 `protobuf:"varint,4,opt,name=grade,proto3,oneof" json:"grade,omitempty"`                          // Lớp học để lọc
	IsDeleted     *bool                  `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3,oneof" json:"is_deleted,omitempty"` // Lọc theo trạng thái xóa
	Keyword       *string                `protobuf:"bytes,6,opt,name=keyword,proto3,oneof" json:"keyword,omitempty"`                       // Từ khóa tìm kiếm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassRequest) Reset() {
	*x = ListClassRequest{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassRequest) ProtoMessage() {}

func (x *ListClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassRequest.ProtoReflect.Descriptor instead.
func (*ListClassRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{3}
}

func (x *ListClassRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListClassRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListClassRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ListClassRequest) GetGrade() int64 {
	if x != nil && x.Grade != nil {
		return *x.Grade
	}
	return 0
}

func (x *ListClassRequest) GetIsDeleted() bool {
	if x != nil && x.IsDeleted != nil {
		return *x.IsDeleted
	}
	return false
}

func (x *ListClassRequest) GetKeyword() string {
	if x != nil && x.Keyword != nil {
		return *x.Keyword
	}
	return ""
}

type GetClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID của lớp học cần lấy thông tin
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassRequest) Reset() {
	*x = GetClassRequest{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassRequest) ProtoMessage() {}

func (x *GetClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassRequest.ProtoReflect.Descriptor instead.
func (*GetClassRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{4}
}

func (x *GetClassRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListClassReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ClassData           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListClassReply) Reset() {
	*x = ListClassReply{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListClassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListClassReply) ProtoMessage() {}

func (x *ListClassReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListClassReply.ProtoReflect.Descriptor instead.
func (*ListClassReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{5}
}

func (x *ListClassReply) GetItems() []*ClassData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListClassReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetClassReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Class         *ClassData             `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`       // Thông tin lớp học
	Students      []*StudentDataForClass `protobuf:"bytes,2,rep,name=students,proto3" json:"students,omitempty"` // Danh sách học sinh trong lớp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassReply) Reset() {
	*x = GetClassReply{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassReply) ProtoMessage() {}

func (x *GetClassReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassReply.ProtoReflect.Descriptor instead.
func (*GetClassReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{6}
}

func (x *GetClassReply) GetClass() *ClassData {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *GetClassReply) GetStudents() []*StudentDataForClass {
	if x != nil {
		return x.Students
	}
	return nil
}

type StudentDataForClass struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentDataForClass) Reset() {
	*x = StudentDataForClass{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentDataForClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentDataForClass) ProtoMessage() {}

func (x *StudentDataForClass) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentDataForClass.ProtoReflect.Descriptor instead.
func (*StudentDataForClass) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{7}
}

func (x *StudentDataForClass) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentDataForClass) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateClassReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Thông báo kết quả tạo lớp học
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateClassReply) Reset() {
	*x = CreateClassReply{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateClassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateClassReply) ProtoMessage() {}

func (x *CreateClassReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateClassReply.ProtoReflect.Descriptor instead.
func (*CreateClassReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{8}
}

func (x *CreateClassReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateClassReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Thông báo kết quả cập nhật lớp học
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateClassReply) Reset() {
	*x = UpdateClassReply{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateClassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateClassReply) ProtoMessage() {}

func (x *UpdateClassReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateClassReply.ProtoReflect.Descriptor instead.
func (*UpdateClassReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateClassReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteClassReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Thông báo kết quả xóa lớp học
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteClassReply) Reset() {
	*x = DeleteClassReply{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteClassReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteClassReply) ProtoMessage() {}

func (x *DeleteClassReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteClassReply.ProtoReflect.Descriptor instead.
func (*DeleteClassReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteClassReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClassData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Grade         int64                  `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`
	IsDeleted     *bool                  `protobuf:"varint,4,opt,name=is_deleted,proto3,oneof" json:"is_deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassData) Reset() {
	*x = ClassData{}
	mi := &file_api_helloworld_v1_class_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassData) ProtoMessage() {}

func (x *ClassData) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_class_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassData.ProtoReflect.Descriptor instead.
func (*ClassData) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_class_proto_rawDescGZIP(), []int{11}
}

func (x *ClassData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClassData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClassData) GetGrade() int64 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *ClassData) GetIsDeleted() bool {
	if x != nil && x.IsDeleted != nil {
		return *x.IsDeleted
	}
	return false
}

var File_api_helloworld_v1_class_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_class_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/helloworld/v1/class.proto\x12\rhelloworld.v1\">\n" +
	"\x12CreateClassRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05grade\x18\x02 \x01(\x03R\x05grade\"N\n" +
	"\x12UpdateClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\x03R\x05grade\"$\n" +
	"\x12DeleteClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe8\x01\n" +
	"\x10ListClassRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05grade\x18\x04 \x01(\x03H\x01R\x05grade\x88\x01\x01\x12\"\n" +
	"\n" +
	"is_deleted\x18\x05 \x01(\bH\x02R\tisDeleted\x88\x01\x01\x12\x1d\n" +
	"\akeyword\x18\x06 \x01(\tH\x03R\akeyword\x88\x01\x01B\a\n" +
	"\x05_nameB\b\n" +
	"\x06_gradeB\r\n" +
	"\v_is_deletedB\n" +
	"\n" +
	"\b_keyword\"!\n" +
	"\x0fGetClassRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"V\n" +
	"\x0eListClassReply\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.helloworld.v1.ClassDataR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x7f\n" +
	"\rGetClassReply\x12.\n" +
	"\x05class\x18\x01 \x01(\v2\x18.helloworld.v1.ClassDataR\x05class\x12>\n" +
	"\bstudents\x18\x02 \x03(\v2\".helloworld.v1.StudentDataForClassR\bstudents\"9\n" +
	"\x13StudentDataForClass\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x10CreateClassReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x10UpdateClassReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\",\n" +
	"\x10DeleteClassReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"y\n" +
	"\tClassData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\x03R\x05grade\x12#\n" +
	"\n" +
	"is_deleted\x18\x04 \x01(\bH\x00R\n" +
	"is_deleted\x88\x01\x01B\r\n" +
	"\v_is_deletedB\x1eZ\x1cDemoApp/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_class_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_class_proto_rawDescData []byte
)

func file_api_helloworld_v1_class_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_class_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_class_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_class_proto_rawDesc), len(file_api_helloworld_v1_class_proto_rawDesc)))
	})
	return file_api_helloworld_v1_class_proto_rawDescData
}

var file_api_helloworld_v1_class_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_helloworld_v1_class_proto_goTypes = []any{
	(*CreateClassRequest)(nil),  // 0: helloworld.v1.CreateClassRequest
	(*UpdateClassRequest)(nil),  // 1: helloworld.v1.UpdateClassRequest
	(*DeleteClassRequest)(nil),  // 2: helloworld.v1.DeleteClassRequest
	(*ListClassRequest)(nil),    // 3: helloworld.v1.ListClassRequest
	(*GetClassRequest)(nil),     // 4: helloworld.v1.GetClassRequest
	(*ListClassReply)(nil),      // 5: helloworld.v1.ListClassReply
	(*GetClassReply)(nil),       // 6: helloworld.v1.GetClassReply
	(*StudentDataForClass)(nil), // 7: helloworld.v1.StudentDataForClass
	(*CreateClassReply)(nil),    // 8: helloworld.v1.CreateClassReply
	(*UpdateClassReply)(nil),    // 9: helloworld.v1.UpdateClassReply
	(*DeleteClassReply)(nil),    // 10: helloworld.v1.DeleteClassReply
	(*ClassData)(nil),           // 11: helloworld.v1.ClassData
}
var file_api_helloworld_v1_class_proto_depIdxs = []int32{
	11, // 0: helloworld.v1.ListClassReply.items:type_name -> helloworld.v1.ClassData
	11, // 1: helloworld.v1.GetClassReply.class:type_name -> helloworld.v1.ClassData
	7,  // 2: helloworld.v1.GetClassReply.students:type_name -> helloworld.v1.StudentDataForClass
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_class_proto_init() }
func file_api_helloworld_v1_class_proto_init() {
	if File_api_helloworld_v1_class_proto != nil {
		return
	}
	file_api_helloworld_v1_class_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_helloworld_v1_class_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_class_proto_rawDesc), len(file_api_helloworld_v1_class_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_helloworld_v1_class_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_class_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_class_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_class_proto = out.File
	file_api_helloworld_v1_class_proto_goTypes = nil
	file_api_helloworld_v1_class_proto_depIdxs = nil
}
