// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/helloworld/v1/teacher.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request để lấy 1 giáo viên theo ID
// kratos proto client ./api/helloworld/v1/teacher.proto
type GetTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeacherRequest) Reset() {
	*x = GetTeacherRequest{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeacherRequest) ProtoMessage() {}

func (x *GetTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeacherRequest.ProtoReflect.Descriptor instead.
func (*GetTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{0}
}

func (x *GetTeacherRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Response khi trả về thông tin giáo viên
type TeacherReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ClassName     string                 `protobuf:"bytes,4,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Age           int32                  `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeacherReply) Reset() {
	*x = TeacherReply{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeacherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeacherReply) ProtoMessage() {}

func (x *TeacherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeacherReply.ProtoReflect.Descriptor instead.
func (*TeacherReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{1}
}

func (x *TeacherReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TeacherReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TeacherReply) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TeacherReply) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *TeacherReply) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// Request để tạo mới giáo viên
type CreateTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	ClassId       int32                  `protobuf:"varint,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeacherRequest) Reset() {
	*x = CreateTeacherRequest{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeacherRequest) ProtoMessage() {}

func (x *CreateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeacherRequest.ProtoReflect.Descriptor instead.
func (*CreateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTeacherRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTeacherRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateTeacherRequest) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *CreateTeacherRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type UpdateTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *int64                 `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Age           *int32                 `protobuf:"varint,4,opt,name=age,proto3,oneof" json:"age,omitempty"`
	ClassId       *int64                 `protobuf:"varint,5,opt,name=class_id,json=classId,proto3,oneof" json:"class_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeacherRequest) Reset() {
	*x = UpdateTeacherRequest{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherRequest) ProtoMessage() {}

func (x *UpdateTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherRequest.ProtoReflect.Descriptor instead.
func (*UpdateTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTeacherRequest) GetId() int64 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *UpdateTeacherRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTeacherRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateTeacherRequest) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

func (x *UpdateTeacherRequest) GetClassId() int64 {
	if x != nil && x.ClassId != nil {
		return *x.ClassId
	}
	return 0
}

type DeleteTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // ID của giáo viên cần xóa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherRequest) Reset() {
	*x = DeleteTeacherRequest{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherRequest) ProtoMessage() {}

func (x *DeleteTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherRequest.ProtoReflect.Descriptor instead.
func (*DeleteTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteTeacherRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Request để lấy danh sách tất cả giáo viên
type ListTeachersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          uint32                 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      uint32                 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Fitler        *FilterTeacherRequest  `protobuf:"bytes,3,opt,name=fitler,proto3,oneof" json:"fitler,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersRequest) Reset() {
	*x = ListTeachersRequest{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersRequest) ProtoMessage() {}

func (x *ListTeachersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersRequest.ProtoReflect.Descriptor instead.
func (*ListTeachersRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{5}
}

func (x *ListTeachersRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTeachersRequest) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTeachersRequest) GetFitler() *FilterTeacherRequest {
	if x != nil {
		return x.Fitler
	}
	return nil
}

type FilterTeacherRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxAge        *int32                 `protobuf:"varint,1,opt,name=maxAge,proto3,oneof" json:"maxAge,omitempty"`
	MinAge        *int32                 `protobuf:"varint,2,opt,name=minAge,proto3,oneof" json:"minAge,omitempty"`
	Email         *string                `protobuf:"bytes,3,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterTeacherRequest) Reset() {
	*x = FilterTeacherRequest{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterTeacherRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterTeacherRequest) ProtoMessage() {}

func (x *FilterTeacherRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterTeacherRequest.ProtoReflect.Descriptor instead.
func (*FilterTeacherRequest) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{6}
}

func (x *FilterTeacherRequest) GetMaxAge() int32 {
	if x != nil && x.MaxAge != nil {
		return *x.MaxAge
	}
	return 0
}

func (x *FilterTeacherRequest) GetMinAge() int32 {
	if x != nil && x.MinAge != nil {
		return *x.MinAge
	}
	return 0
}

func (x *FilterTeacherRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

// Response khi tạo xong giáo viên
type CreateTeacherReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTeacherReply) Reset() {
	*x = CreateTeacherReply{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTeacherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTeacherReply) ProtoMessage() {}

func (x *CreateTeacherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTeacherReply.ProtoReflect.Descriptor instead.
func (*CreateTeacherReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTeacherReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteTeacherReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Thông báo kết quả xóa
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTeacherReply) Reset() {
	*x = DeleteTeacherReply{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeacherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeacherReply) ProtoMessage() {}

func (x *DeleteTeacherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTeacherReply.ProtoReflect.Descriptor instead.
func (*DeleteTeacherReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTeacherReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateTeacherReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // Thông báo kết quả cập nhật
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTeacherReply) Reset() {
	*x = UpdateTeacherReply{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTeacherReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTeacherReply) ProtoMessage() {}

func (x *UpdateTeacherReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTeacherReply.ProtoReflect.Descriptor instead.
func (*UpdateTeacherReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateTeacherReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Response trả về danh sách giáo viên
type ListTeachersReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Teachers      []*TeacherReply        `protobuf:"bytes,1,rep,name=teachers,proto3" json:"teachers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTeachersReply) Reset() {
	*x = ListTeachersReply{}
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTeachersReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTeachersReply) ProtoMessage() {}

func (x *ListTeachersReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_helloworld_v1_teacher_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTeachersReply.ProtoReflect.Descriptor instead.
func (*ListTeachersReply) Descriptor() ([]byte, []int) {
	return file_api_helloworld_v1_teacher_proto_rawDescGZIP(), []int{10}
}

func (x *ListTeachersReply) GetTeachers() []*TeacherReply {
	if x != nil {
		return x.Teachers
	}
	return nil
}

var File_api_helloworld_v1_teacher_proto protoreflect.FileDescriptor

const file_api_helloworld_v1_teacher_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/helloworld/v1/teacher.proto\x12\rhelloworld.v1\x1a\x1cgoogle/api/annotations.proto\"#\n" +
	"\x11GetTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"y\n" +
	"\fTeacherReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"class_name\x18\x04 \x01(\tR\tclassName\x12\x10\n" +
	"\x03age\x18\x05 \x01(\x05R\x03age\"m\n" +
	"\x14CreateTeacherRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\x05R\aclassId\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\"\xc5\x01\n" +
	"\x14UpdateTeacherRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\x03H\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x02R\x05email\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x04 \x01(\x05H\x03R\x03age\x88\x01\x01\x12\x1e\n" +
	"\bclass_id\x18\x05 \x01(\x03H\x04R\aclassId\x88\x01\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\b\n" +
	"\x06_emailB\x06\n" +
	"\x04_ageB\v\n" +
	"\t_class_id\"&\n" +
	"\x14DeleteTeacherRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x93\x01\n" +
	"\x13ListTeachersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\rR\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12@\n" +
	"\x06fitler\x18\x03 \x01(\v2#.helloworld.v1.FilterTeacherRequestH\x00R\x06fitler\x88\x01\x01B\t\n" +
	"\a_fitler\"\x8b\x01\n" +
	"\x14FilterTeacherRequest\x12\x1b\n" +
	"\x06maxAge\x18\x01 \x01(\x05H\x00R\x06maxAge\x88\x01\x01\x12\x1b\n" +
	"\x06minAge\x18\x02 \x01(\x05H\x01R\x06minAge\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\x03 \x01(\tH\x02R\x05email\x88\x01\x01B\t\n" +
	"\a_maxAgeB\t\n" +
	"\a_minAgeB\b\n" +
	"\x06_email\".\n" +
	"\x12CreateTeacherReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x12DeleteTeacherReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\".\n" +
	"\x12UpdateTeacherReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"L\n" +
	"\x11ListTeachersReply\x127\n" +
	"\bteachers\x18\x01 \x03(\v2\x1b.helloworld.v1.TeacherReplyR\bteachers2\xce\x04\n" +
	"\x0eTeacherService\x12h\n" +
	"\n" +
	"GetTeacher\x12 .helloworld.v1.GetTeacherRequest\x1a\x1b.helloworld.v1.TeacherReply\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13api/v1/teacher/{id}\x12r\n" +
	"\rCreateTeacher\x12#.helloworld.v1.CreateTeacherRequest\x1a!.helloworld.v1.CreateTeacherReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0eapi/v1/teacher\x12t\n" +
	"\fListTeachers\x12\".helloworld.v1.ListTeachersRequest\x1a .helloworld.v1.ListTeachersReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13api/v1/teacher/list\x12r\n" +
	"\rUpdateTeacher\x12#.helloworld.v1.UpdateTeacherRequest\x1a!.helloworld.v1.UpdateTeacherReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0eapi/v1/teacher\x12t\n" +
	"\rDeleteTeacher\x12#.helloworld.v1.DeleteTeacherRequest\x1a!.helloworld.v1.DeleteTeacherReply\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13api/v1/teacher/{id}B\x1eZ\x1cDemoApp/api/helloworld/v1;v1b\x06proto3"

var (
	file_api_helloworld_v1_teacher_proto_rawDescOnce sync.Once
	file_api_helloworld_v1_teacher_proto_rawDescData []byte
)

func file_api_helloworld_v1_teacher_proto_rawDescGZIP() []byte {
	file_api_helloworld_v1_teacher_proto_rawDescOnce.Do(func() {
		file_api_helloworld_v1_teacher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_teacher_proto_rawDesc), len(file_api_helloworld_v1_teacher_proto_rawDesc)))
	})
	return file_api_helloworld_v1_teacher_proto_rawDescData
}

var file_api_helloworld_v1_teacher_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_helloworld_v1_teacher_proto_goTypes = []any{
	(*GetTeacherRequest)(nil),    // 0: helloworld.v1.GetTeacherRequest
	(*TeacherReply)(nil),         // 1: helloworld.v1.TeacherReply
	(*CreateTeacherRequest)(nil), // 2: helloworld.v1.CreateTeacherRequest
	(*UpdateTeacherRequest)(nil), // 3: helloworld.v1.UpdateTeacherRequest
	(*DeleteTeacherRequest)(nil), // 4: helloworld.v1.DeleteTeacherRequest
	(*ListTeachersRequest)(nil),  // 5: helloworld.v1.ListTeachersRequest
	(*FilterTeacherRequest)(nil), // 6: helloworld.v1.FilterTeacherRequest
	(*CreateTeacherReply)(nil),   // 7: helloworld.v1.CreateTeacherReply
	(*DeleteTeacherReply)(nil),   // 8: helloworld.v1.DeleteTeacherReply
	(*UpdateTeacherReply)(nil),   // 9: helloworld.v1.UpdateTeacherReply
	(*ListTeachersReply)(nil),    // 10: helloworld.v1.ListTeachersReply
}
var file_api_helloworld_v1_teacher_proto_depIdxs = []int32{
	6,  // 0: helloworld.v1.ListTeachersRequest.fitler:type_name -> helloworld.v1.FilterTeacherRequest
	1,  // 1: helloworld.v1.ListTeachersReply.teachers:type_name -> helloworld.v1.TeacherReply
	0,  // 2: helloworld.v1.TeacherService.GetTeacher:input_type -> helloworld.v1.GetTeacherRequest
	2,  // 3: helloworld.v1.TeacherService.CreateTeacher:input_type -> helloworld.v1.CreateTeacherRequest
	5,  // 4: helloworld.v1.TeacherService.ListTeachers:input_type -> helloworld.v1.ListTeachersRequest
	3,  // 5: helloworld.v1.TeacherService.UpdateTeacher:input_type -> helloworld.v1.UpdateTeacherRequest
	4,  // 6: helloworld.v1.TeacherService.DeleteTeacher:input_type -> helloworld.v1.DeleteTeacherRequest
	1,  // 7: helloworld.v1.TeacherService.GetTeacher:output_type -> helloworld.v1.TeacherReply
	7,  // 8: helloworld.v1.TeacherService.CreateTeacher:output_type -> helloworld.v1.CreateTeacherReply
	10, // 9: helloworld.v1.TeacherService.ListTeachers:output_type -> helloworld.v1.ListTeachersReply
	9,  // 10: helloworld.v1.TeacherService.UpdateTeacher:output_type -> helloworld.v1.UpdateTeacherReply
	8,  // 11: helloworld.v1.TeacherService.DeleteTeacher:output_type -> helloworld.v1.DeleteTeacherReply
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_helloworld_v1_teacher_proto_init() }
func file_api_helloworld_v1_teacher_proto_init() {
	if File_api_helloworld_v1_teacher_proto != nil {
		return
	}
	file_api_helloworld_v1_teacher_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_helloworld_v1_teacher_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_helloworld_v1_teacher_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_helloworld_v1_teacher_proto_rawDesc), len(file_api_helloworld_v1_teacher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_helloworld_v1_teacher_proto_goTypes,
		DependencyIndexes: file_api_helloworld_v1_teacher_proto_depIdxs,
		MessageInfos:      file_api_helloworld_v1_teacher_proto_msgTypes,
	}.Build()
	File_api_helloworld_v1_teacher_proto = out.File
	file_api_helloworld_v1_teacher_proto_goTypes = nil
	file_api_helloworld_v1_teacher_proto_depIdxs = nil
}
